name: Trigger binder build

on: [push, pull_request]

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: alexjbest/notebooks
